/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kinire.proyectointegrador.desktop.ui.frame;

import com.kinire.proyectointegrador.client.Connection;
import com.kinire.proyectointegrador.components.Product;
import com.kinire.proyectointegrador.desktop.controller.MainFrameController;
import com.kinire.proyectointegrador.desktop.ui.list_renderer.CustomRenderer;
import com.kinire.proyectointegrador.desktop.utils.ImageCache;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.io.ByteArrayInputStream;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author kinire
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */

    private final static String TITLE = "Karrefú";


    private final static Color MAIN_BLUE = new Color(21, 94, 149);
    private List<Product> products;
    private final DefaultListModel<Product> listModel = new DefaultListModel<>();

    private int i = 0;// No es una variable local por las lambdas

    private boolean connectionStarted = false;

    private final MainFrameController controller;

    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        this.products = new ArrayList<>();
        initList();
        setTitle(TITLE);
        System.setProperty("java.awt.application.name", TITLE);
        this.controller = new MainFrameController(this);
        productsList.addMouseListener(controller);
    }


    private void initList() {
        i = 0;
        listModel.clear();
        if(!connectionStarted) {
            Connection.startInstance(() -> {
                Connection.getInstance().setConnectionLostPromise(() -> {
                    // TODO: connection lost promise here
                });
                Connection.getInstance().setProductsUpdatedPromise(() -> {
                    initList();
                });
                Connection.getInstance().getProducts(product -> {
                    try {
                        ImageCache.putImage(product.getImagePath(), new ImageIcon(ImageIO.read(new ByteArrayInputStream(product.getImage()))));
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    SwingUtilities.invokeLater(() -> {
                        listModel.add(i, product);
                        i++;
                    });
                }, e -> {

                });
            });
            connectionStarted = true;
        } else {
            Connection.getInstance().getProducts(product -> {
                try {
                    ImageCache.putImage(product.getImagePath(), new ImageIcon(ImageIO.read(new ByteArrayInputStream(product.getImage()))));
                } catch (Exception e) {
                    e.printStackTrace();
                }
                listModel.add(i, product);
                i++;
                productsList.setModel(listModel);
            }, e -> {

            });
        }

        productsList.setModel(listModel);
        productsList.setCellRenderer(new CustomRenderer());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new com.kinire.proyectointegrador.components.User();
        currentPurchase = new com.kinire.proyectointegrador.components.Purchase();
        mainPanel = new javax.swing.JPanel();
        settingsButton = new javax.swing.JButton();
        purchaseHistoryButton = new javax.swing.JButton();
        emptyPurchaseButton = new javax.swing.JButton();
        savePurchaseButton = new javax.swing.JButton();
        productsPanel = new javax.swing.JPanel();
        productsLabel = new javax.swing.JLabel();
        productsScroll = new javax.swing.JScrollPane();
        productsList = new javax.swing.JList();
        shoppingCartPanel = new javax.swing.JPanel();
        shoppingCartLabel = new javax.swing.JLabel();
        shoppingCartItemsScroll = new javax.swing.JScrollPane();
        shoppingCartTable = new javax.swing.JTable();
        roundedPanel2 = new com.kinire.proyectointegrador.desktop.ui.modifiedComponents.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        notWellSeenLabel1 = new javax.swing.JLabel();
        notWellSeenLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveTo = new javax.swing.JMenuItem();
        open = new javax.swing.JMenuItem();
        addProduct = new javax.swing.JMenu();
        changeUser = new javax.swing.JMenuItem();
        Products = new javax.swing.JMenu();
        openProductView = new javax.swing.JMenuItem();
        shoppingCartMenu = new javax.swing.JMenu();
        savePurchaseMenu = new javax.swing.JMenuItem();
        emptyPurchaseMenu = new javax.swing.JMenuItem();
        previousPurchasesMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        settingsButton.setBackground(new java.awt.Color(21, 94, 149));
        settingsButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        settingsButton.setForeground(new java.awt.Color(255, 255, 255));
        settingsButton.setText("Ajustes");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        purchaseHistoryButton.setBackground(new java.awt.Color(21, 94, 149));
        purchaseHistoryButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        purchaseHistoryButton.setForeground(new java.awt.Color(255, 255, 255));
        purchaseHistoryButton.setText("Ver historial");
        purchaseHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseHistoryButtonActionPerformed(evt);
            }
        });

        emptyPurchaseButton.setBackground(new java.awt.Color(21, 94, 149));
        emptyPurchaseButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        emptyPurchaseButton.setForeground(new java.awt.Color(255, 255, 255));
        emptyPurchaseButton.setText("Vaciar compra");
        emptyPurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyPurchaseButtonActionPerformed(evt);
            }
        });

        savePurchaseButton.setBackground(new java.awt.Color(21, 94, 149));
        savePurchaseButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        savePurchaseButton.setForeground(new java.awt.Color(255, 255, 255));
        savePurchaseButton.setText("Guardar compra");
        savePurchaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePurchaseButtonActionPerformed(evt);
            }
        });

        productsLabel.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        productsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productsLabel.setText("Productos");

        productsList.setModel(this.listModel);
        productsScroll.setViewportView(productsList);

        javax.swing.GroupLayout productsPanelLayout = new javax.swing.GroupLayout(productsPanel);
        productsPanel.setLayout(productsPanelLayout);
        productsPanelLayout.setHorizontalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(productsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        productsPanelLayout.setVerticalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addComponent(productsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(productsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        shoppingCartLabel.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        shoppingCartLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shoppingCartLabel.setText("Carrito");

        shoppingCartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Precio unitario", "Cantidad", "Precio total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        shoppingCartItemsScroll.setViewportView(shoppingCartTable);

        javax.swing.GroupLayout shoppingCartPanelLayout = new javax.swing.GroupLayout(shoppingCartPanel);
        shoppingCartPanel.setLayout(shoppingCartPanelLayout);
        shoppingCartPanelLayout.setHorizontalGroup(
            shoppingCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingCartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shoppingCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shoppingCartItemsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shoppingCartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
                .addContainerGap())
        );
        shoppingCartPanelLayout.setVerticalGroup(
            shoppingCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingCartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shoppingCartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shoppingCartItemsScroll))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Precio");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1)
                .addContainerGap())
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        notWellSeenLabel1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        notWellSeenLabel1.setText("Si los productos no se ven bien,");

        notWellSeenLabel2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        notWellSeenLabel2.setForeground(new java.awt.Color(21, 94, 149));
        notWellSeenLabel2.setText("<html><a>pulsa aquí</a></html>");
        notWellSeenLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                notWellSeenLabel2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(productsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(shoppingCartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emptyPurchaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(savePurchaseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(purchaseHistoryButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roundedPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(notWellSeenLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notWellSeenLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(purchaseHistoryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emptyPurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(savePurchaseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(shoppingCartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notWellSeenLabel1)
                    .addComponent(notWellSeenLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        fileMenu.setText("Archivo");

        saveTo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveTo.setText("Guardar compra");
        saveTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToActionPerformed(evt);
            }
        });
        fileMenu.add(saveTo);

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        open.setText("Cargar compra");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        fileMenu.add(open);

        menuBar.add(fileMenu);

        addProduct.setText("Usuario");

        changeUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        changeUser.setText("Cambiar usuario");
        changeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserActionPerformed(evt);
            }
        });
        addProduct.add(changeUser);

        menuBar.add(addProduct);

        Products.setText("Producto");

        openProductView.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openProductView.setText("Añadir producto");
        openProductView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProductViewActionPerformed(evt);
            }
        });
        Products.add(openProductView);

        menuBar.add(Products);

        shoppingCartMenu.setText("Carrito");

        savePurchaseMenu.setText("Guardar compra");
        savePurchaseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePurchaseMenuActionPerformed(evt);
            }
        });
        shoppingCartMenu.add(savePurchaseMenu);

        emptyPurchaseMenu.setText("Vaciar compras");
        emptyPurchaseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyPurchaseMenuActionPerformed(evt);
            }
        });
        shoppingCartMenu.add(emptyPurchaseMenu);

        previousPurchasesMenu.setText("Ver compras anteriores");
        previousPurchasesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousPurchasesMenuActionPerformed(evt);
            }
        });
        shoppingCartMenu.add(previousPurchasesMenu);

        menuBar.add(shoppingCartMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void purchaseHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseHistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseHistoryButtonActionPerformed

    private void emptyPurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyPurchaseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emptyPurchaseButtonActionPerformed

    private void savePurchaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePurchaseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savePurchaseButtonActionPerformed

    private void previousPurchasesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousPurchasesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousPurchasesMenuActionPerformed

    private void emptyPurchaseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyPurchaseMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emptyPurchaseMenuActionPerformed

    private void savePurchaseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePurchaseMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savePurchaseMenuActionPerformed

    private void openProductViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProductViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openProductViewActionPerformed

    private void changeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeUserActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openActionPerformed

    private void saveToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveToActionPerformed

    private void notWellSeenLabel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notWellSeenLabel2MouseReleased
        initList();
    }//GEN-LAST:event_notWellSeenLabel2MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Products;
    private javax.swing.JMenu addProduct;
    private javax.swing.JMenuItem changeUser;
    private com.kinire.proyectointegrador.components.Purchase currentPurchase;
    private javax.swing.JButton emptyPurchaseButton;
    private javax.swing.JMenuItem emptyPurchaseMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel notWellSeenLabel1;
    private javax.swing.JLabel notWellSeenLabel2;
    private javax.swing.JMenuItem open;
    private javax.swing.JMenuItem openProductView;
    private javax.swing.JMenuItem previousPurchasesMenu;
    private javax.swing.JLabel productsLabel;
    private javax.swing.JList<Product> productsList;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JScrollPane productsScroll;
    private javax.swing.JButton purchaseHistoryButton;
    private com.kinire.proyectointegrador.desktop.ui.modifiedComponents.RoundedPanel roundedPanel2;
    private javax.swing.JButton savePurchaseButton;
    private javax.swing.JMenuItem savePurchaseMenu;
    private javax.swing.JMenuItem saveTo;
    private javax.swing.JButton settingsButton;
    private javax.swing.JScrollPane shoppingCartItemsScroll;
    private javax.swing.JLabel shoppingCartLabel;
    private javax.swing.JMenu shoppingCartMenu;
    private javax.swing.JPanel shoppingCartPanel;
    private javax.swing.JTable shoppingCartTable;
    private com.kinire.proyectointegrador.components.User user;
    // End of variables declaration//GEN-END:variables
}
