/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kinire.proyectointegrador.desktop.ui.frame;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author kinire
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private final static Color mainBlue = new Color(21, 94, 149);
    public MainFrame() {
        UIManager.put("MenuBar.background", mainBlue);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user = new com.kinire.proyectointegrador.components.User();
        currentPurchase = new com.kinire.proyectointegrador.components.Purchase();
        mainPanel = new javax.swing.JPanel();
        settingsButton = new javax.swing.JButton();
        savePurchase = new javax.swing.JButton();
        emptyPurchase = new javax.swing.JButton();
        seePurchases = new javax.swing.JButton();
        productsPanel = new javax.swing.JPanel();
        productsLabel = new javax.swing.JLabel();
        productsScroll = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        shoppingCartPanel = new javax.swing.JPanel();
        shoppingCartLabel = new javax.swing.JLabel();
        shoppingCartItemsScroll = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        roundedPanel2 = new com.kinire.proyectointegrador.desktop.ui.modifiedComponents.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        saveTo = new javax.swing.JMenuItem();
        open = new javax.swing.JMenuItem();
        userMenu = new javax.swing.JMenu();
        changeUser = new javax.swing.JMenuItem();
        Products = new javax.swing.JMenu();
        openProductView = new javax.swing.JMenuItem();
        shoppingCartMenu = new javax.swing.JMenu();
        savePurchaseMenu = new javax.swing.JMenuItem();
        emptyPurchaseMenu = new javax.swing.JMenuItem();
        previousPurchasesMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        settingsButton.setBackground(new java.awt.Color(21, 94, 149));
        settingsButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        settingsButton.setForeground(new java.awt.Color(255, 255, 255));
        settingsButton.setText("Ajustes");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        savePurchase.setBackground(new java.awt.Color(21, 94, 149));
        savePurchase.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        savePurchase.setForeground(new java.awt.Color(255, 255, 255));
        savePurchase.setText("Guardar compra");
        savePurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePurchaseActionPerformed(evt);
            }
        });

        emptyPurchase.setBackground(new java.awt.Color(21, 94, 149));
        emptyPurchase.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        emptyPurchase.setForeground(new java.awt.Color(255, 255, 255));
        emptyPurchase.setText("Vaciar compra");
        emptyPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyPurchaseActionPerformed(evt);
            }
        });

        seePurchases.setBackground(new java.awt.Color(21, 94, 149));
        seePurchases.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        seePurchases.setForeground(new java.awt.Color(255, 255, 255));
        seePurchases.setText("Ver compras");
        seePurchases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seePurchasesActionPerformed(evt);
            }
        });

        productsLabel.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        productsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productsLabel.setText("Productos");

        productsScroll.setViewportView(jList1);

        javax.swing.GroupLayout productsPanelLayout = new javax.swing.GroupLayout(productsPanel);
        productsPanel.setLayout(productsPanelLayout);
        productsPanelLayout.setHorizontalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(productsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        productsPanelLayout.setVerticalGroup(
            productsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productsPanelLayout.createSequentialGroup()
                .addComponent(productsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(productsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        shoppingCartLabel.setFont(new java.awt.Font("Dialog", 1, 32)); // NOI18N
        shoppingCartLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shoppingCartLabel.setText("Carrito");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        shoppingCartItemsScroll.setViewportView(jTable1);

        javax.swing.GroupLayout shoppingCartPanelLayout = new javax.swing.GroupLayout(shoppingCartPanel);
        shoppingCartPanel.setLayout(shoppingCartPanelLayout);
        shoppingCartPanelLayout.setHorizontalGroup(
            shoppingCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingCartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shoppingCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shoppingCartItemsScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shoppingCartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addContainerGap())
        );
        shoppingCartPanelLayout.setVerticalGroup(
            shoppingCartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shoppingCartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(shoppingCartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shoppingCartItemsScroll))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Precio");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1)
                .addContainerGap())
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(productsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(shoppingCartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emptyPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seePurchases, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(savePurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roundedPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(savePurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emptyPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(seePurchases, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(shoppingCartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        fileMenu.setText("Archivo");

        saveTo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveTo.setText("Guardar compra");
        saveTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToActionPerformed(evt);
            }
        });
        fileMenu.add(saveTo);

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        open.setText("Cargar compra");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        fileMenu.add(open);

        menuBar.add(fileMenu);

        userMenu.setText("Usuario");

        changeUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        changeUser.setText("Cambiar usuario");
        changeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserActionPerformed(evt);
            }
        });
        userMenu.add(changeUser);

        menuBar.add(userMenu);

        Products.setText("Producto");

        openProductView.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openProductView.setText("Abrir vista de producto");
        openProductView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProductViewActionPerformed(evt);
            }
        });
        Products.add(openProductView);

        menuBar.add(Products);

        shoppingCartMenu.setText("Carrito");

        savePurchaseMenu.setText("Guardar compra");
        savePurchaseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePurchaseMenuActionPerformed(evt);
            }
        });
        shoppingCartMenu.add(savePurchaseMenu);

        emptyPurchaseMenu.setText("Vaciar compras");
        emptyPurchaseMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyPurchaseMenuActionPerformed(evt);
            }
        });
        shoppingCartMenu.add(emptyPurchaseMenu);

        previousPurchasesMenu.setText("Ver compras anteriores");
        previousPurchasesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousPurchasesMenuActionPerformed(evt);
            }
        });
        shoppingCartMenu.add(previousPurchasesMenu);

        menuBar.add(shoppingCartMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void savePurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePurchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savePurchaseActionPerformed

    private void emptyPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyPurchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emptyPurchaseActionPerformed

    private void seePurchasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seePurchasesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seePurchasesActionPerformed

    private void previousPurchasesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousPurchasesMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previousPurchasesMenuActionPerformed

    private void emptyPurchaseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyPurchaseMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emptyPurchaseMenuActionPerformed

    private void savePurchaseMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePurchaseMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savePurchaseMenuActionPerformed

    private void openProductViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProductViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openProductViewActionPerformed

    private void changeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeUserActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openActionPerformed

    private void saveToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveToActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Products;
    private javax.swing.JMenuItem changeUser;
    private com.kinire.proyectointegrador.components.Purchase currentPurchase;
    private javax.swing.JButton emptyPurchase;
    private javax.swing.JMenuItem emptyPurchaseMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem open;
    private javax.swing.JMenuItem openProductView;
    private javax.swing.JMenuItem previousPurchasesMenu;
    private javax.swing.JLabel productsLabel;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JScrollPane productsScroll;
    private com.kinire.proyectointegrador.desktop.ui.modifiedComponents.RoundedPanel roundedPanel2;
    private javax.swing.JButton savePurchase;
    private javax.swing.JMenuItem savePurchaseMenu;
    private javax.swing.JMenuItem saveTo;
    private javax.swing.JButton seePurchases;
    private javax.swing.JButton settingsButton;
    private javax.swing.JScrollPane shoppingCartItemsScroll;
    private javax.swing.JLabel shoppingCartLabel;
    private javax.swing.JMenu shoppingCartMenu;
    private javax.swing.JPanel shoppingCartPanel;
    private com.kinire.proyectointegrador.components.User user;
    private javax.swing.JMenu userMenu;
    // End of variables declaration//GEN-END:variables
}
